### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by ShahirTurkmen** [zainabturkmen/Restaurant-OrderingApp#1]

**Comment by ShahirTurkmen** [comment]
UPDATING README.md

**Comment by zainabturkmen** [comment]
Hi my dear little cute  Shahir thanks for your comment

![MuaKissGIF](https://github.com/zainabturkmen/Restaurant-OrderingApp/assets/132147692/bad7c498-b4d6-48b7-a08a-f0829fa14495)

**Comment by ShahirTurkmen** [comment]
YOU ARE THE BEST !!!!!!!!!!!!!
My dear!

**Comment by zainabturkmen** [comment]
Thanks but 

![ScalerCreateImpactGIF (2)](https://github.com/zainabturkmen/Restaurant-OrderingApp/assets/132147692/9c9051a9-e1b0-41ff-9cc8-f804f3fd900d)

**Comment by zainabturkmen** [comment]
Thanks but 

![Uploading ScalerCreateImpactGIF.gif…]()
